import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Start seeding...');

  // Create default settings if they don't exist
  const existingSettings = await prisma.settings.findFirst();
  if (!existingSettings) {
    await prisma.settings.create({
      data: {
        siteName: 'Forge & Steel',
        siteDescription: "Premium Men's Jewelry",
        contactEmail: 'contact@forgesteel.com',
        contactPhone: '+972-50-123-4567',
        address: '123 Main Street, Tel Aviv, Israel',
        currency: 'ILS',
        currencySymbol: '₪',
        taxRate: 17,
      },
    });
    console.log('Default settings created');
  }

  // Create Categories with multilingual support
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: 'signature-rings' },
      update: {},
      create: {
        name: 'Signature Rings',
        nameEn: 'Signature Rings',
        nameHe: 'טבעות חתימה',
        slug: 'signature-rings',
        description: 'Bold statement pieces for the modern gentleman',
        image: '/images/category_rings.png',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'wedding-bands' },
      update: {},
      create: {
        name: 'Wedding Bands',
        nameEn: 'Wedding Bands',
        nameHe: 'טבעות נישואין',
        slug: 'wedding-bands',
        description: 'Timeless symbols of commitment',
        image: '/images/wedding-rinfs.jpg',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'custom-pieces' },
      update: {},
      create: {
        name: 'Custom Pieces',
        nameEn: 'Custom Pieces',
        nameHe: 'יצירות מותאמות אישית',
        slug: 'custom-pieces',
        description: 'Bespoke jewelry crafted to your vision',
        image: '/images/ring-4.jpg',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'necklaces' },
      update: {},
      create: {
        name: 'Necklaces',
        nameEn: 'Necklaces',
        nameHe: 'שרשראות',
        slug: 'necklaces',
        description: 'Elegant chains and pendants',
        image: '/images/category-necklaces.png',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'bracelets' },
      update: {},
      create: {
        name: 'Bracelets',
        nameEn: 'Bracelets',
        nameHe: 'צמידים',
        slug: 'bracelets',
        description: 'Sophisticated wrist accessories',
        image: '/images/category-bracelets.png',
      },
    }),
  ]);

  console.log('Categories created:', categories.length);

  // Generate 30 products with diverse data optimized for new indexes
  const products = [
    // Featured Rings (Category 0 - Signature Rings)
    {
      name: 'Obsidian Steel Ring',
      nameEn: 'Obsidian Steel Ring',
      nameHe: 'טבעת פלדת אובסידיאן',
      slug: 'obsidian-steel-ring',
      description:
        'A bold statement piece crafted from premium tungsten carbide with a brushed matte finish.',
      descriptionEn:
        'A bold statement piece crafted from premium tungsten carbide with a brushed matte finish. Perfect for the modern gentleman who values durability and style.',
      descriptionHe:
        "יצירת אמנות נועזת המיוצרת מקרביד טונגסטן פרימיום עם גימור מט מוברש. מושלם לג'נטלמן המודרני המעריך עמידות וסטייל.",
      price: 899,
      comparePrice: 1299,
      image: '/images/product-1.jpg',
      images: [
        '/images/product-1.jpg',
        '/images/rings.jpg',
        '/images/ring-4.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 15,
      categoryId: categories[0].id,
      sku: 'OSR-001',
      lowStockThreshold: 5,
      reorderPoint: 10,
      reorderQuantity: 20,
    },
    {
      name: 'Damascus Steel Band',
      nameEn: 'Damascus Steel Band',
      nameHe: 'טבעת פלדת דמשק',
      slug: 'damascus-steel-band',
      description:
        'Hand-forged Damascus steel ring with unique pattern. Each piece is one-of-a-kind.',
      descriptionEn:
        'Hand-forged Damascus steel ring featuring a mesmerizing wave pattern created through ancient metalworking techniques.',
      descriptionHe:
        'טבעת פלדת דמשק מחושלת ידנית עם דוגמת גלים מהפנטת שנוצרה באמצעות טכניקות עתיקות של עיבוד מתכת.',
      price: 1299,
      comparePrice: 1799,
      image: '/images/product-2.jpg',
      images: [
        '/images/product-2.jpg',
        '/images/ring-black-bg.png',
        '/images/rings.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 8,
      categoryId: categories[0].id,
      sku: 'DSB-002',
      lowStockThreshold: 3,
      reorderPoint: 8,
      reorderQuantity: 15,
    },
    {
      name: 'Carbon Fiber Elite',
      nameEn: 'Carbon Fiber Elite',
      nameHe: 'סיבי פחמן עילית',
      slug: 'carbon-fiber-elite',
      description:
        'Modern design combining aerospace-grade carbon fiber with titanium.',
      descriptionEn:
        'Ultra-modern design combining aerospace-grade carbon fiber with surgical titanium. Incredibly lightweight yet extremely durable.',
      descriptionHe:
        'עיצוב אולטרה-מודרני המשלב סיבי פחמן בדרגה אווירית עם טיטניום כירורגי. קל במשקל להפליא אך עמיד במיוחד.',
      price: 699,
      image: '/images/product-3.jpg',
      images: [
        '/images/product-3.jpg',
        '/images/product-1.jpg',
        '/images/ring-4.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 20,
      categoryId: categories[0].id,
      sku: 'CFE-003',
      lowStockThreshold: 5,
      reorderPoint: 15,
      reorderQuantity: 25,
    },
    {
      name: 'Black Zirconium Pro',
      nameEn: 'Black Zirconium Pro',
      nameHe: 'זירקוניום שחור פרו',
      slug: 'black-zirconium-pro',
      description:
        'Sleek black zirconium ring with natural ceramic oxide finish.',
      descriptionEn:
        'Sleek black zirconium band with permanent black ceramic oxide finish. Scratch-resistant and hypoallergenic.',
      descriptionHe:
        'טבעת זירקוניום שחורה מלוטשה עם גימור תחמוצת קרמית שחורה קבועה. עמידה בפני שריטות והיפואלרגנית.',
      price: 799,
      comparePrice: 999,
      image: '/images/ring-black-bg.png',
      images: [
        '/images/ring-black-bg.png',
        '/images/product-4.jpg',
        '/images/rings.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 18,
      categoryId: categories[0].id,
      sku: 'BZP-004',
      lowStockThreshold: 6,
      reorderPoint: 12,
      reorderQuantity: 20,
    },
    {
      name: 'Titanium Forge',
      nameEn: 'Titanium Forge',
      nameHe: 'מחצבת טיטניום',
      slug: 'titanium-forge',
      description: 'Lightweight titanium ring with brushed finish.',
      descriptionEn:
        'Professional-grade titanium ring with sophisticated brushed finish. Perfect balance of strength and comfort.',
      descriptionHe:
        'טבעת טיטניום בדרגה מקצועית עם גימור מוברש מתוחכם. איזון מושלם של חוזק ונוחות.',
      price: 549,
      image: '/images/product-5.jpg',
      images: [
        '/images/product-5.jpg',
        '/images/ring-4.jpg',
        '/images/product-1.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: true,
      inventory: 25,
      categoryId: categories[0].id,
      sku: 'TF-005',
      lowStockThreshold: 8,
      reorderPoint: 15,
      reorderQuantity: 30,
    },

    // Wedding Bands (Category 1)
    {
      name: 'Eternal Gold Band',
      nameEn: 'Eternal Gold Band',
      nameHe: 'טבעת זהב נצחית',
      slug: 'eternal-gold-band',
      description: 'Classic 18k gold wedding band with polished finish.',
      descriptionEn:
        'Classic 18k gold wedding band with mirror polished finish. A symbol of timeless elegance and eternal commitment.',
      descriptionHe:
        'טבעת נישואין קלאסית מזהב 18 קראט עם גימור מלוטש למראה מראה. סמל של אלגנטיות נצחית ומחויבות נצחית.',
      price: 2499,
      comparePrice: 2999,
      image: '/images/wedding-rinfs.jpg',
      images: [
        '/images/wedding-rinfs.jpg',
        '/images/rings.jpg',
        '/images/product-2.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 12,
      categoryId: categories[1].id,
      sku: 'EGB-006',
      lowStockThreshold: 4,
      reorderPoint: 8,
      reorderQuantity: 15,
    },
    {
      name: 'Platinum Classic',
      nameEn: 'Platinum Classic',
      nameHe: 'פלטינה קלאסית',
      slug: 'platinum-classic',
      description: 'Sophisticated platinum band with comfort fit interior.',
      descriptionEn:
        'Sophisticated platinum band with comfort fit interior and refined brushed finish. Hypoallergenic and tarnish-resistant.',
      descriptionHe:
        'טבעת פלטינה מתוחכמת עם פנים נוחים וגימור מוברש מעודן. היפואלרגנית ועמידה בפני השחתה.',
      price: 3299,
      comparePrice: 3799,
      image: '/images/product-3.jpg',
      images: [
        '/images/product-3.jpg',
        '/images/wedding-rinfs.jpg',
        '/images/rings.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 6,
      categoryId: categories[1].id,
      sku: 'PC-007',
      lowStockThreshold: 2,
      reorderPoint: 5,
      reorderQuantity: 10,
    },
    {
      name: 'Rose Gold Elegance',
      nameEn: 'Rose Gold Elegance',
      nameHe: 'אלגנטיות זהב ורוד',
      slug: 'rose-gold-elegance',
      description: 'Romantic 14k rose gold band with brushed finish.',
      descriptionEn:
        'Romantic 14k rose gold band with brushed finish and beveled edges. The warm pink hue creates a unique contemporary look.',
      descriptionHe:
        'טבעת זהב ורוד רומנטית 14 קראט עם גימור מוברש וקצוות משופעים. הגוון הוורוד החם יוצר מראה ייחודי ועכשווי.',
      price: 1899,
      comparePrice: 2299,
      image: '/images/product-4.jpg',
      images: [
        '/images/product-4.jpg',
        '/images/wedding-rinfs.jpg',
        '/images/product-2.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: true,
      inventory: 10,
      categoryId: categories[1].id,
      sku: 'RGE-008',
      lowStockThreshold: 3,
      reorderPoint: 7,
      reorderQuantity: 12,
    },
    {
      name: 'White Gold Harmony',
      nameEn: 'White Gold Harmony',
      nameHe: 'הרמוניית זהב לבן',
      slug: 'white-gold-harmony',
      description: '14k white gold band with contemporary styling.',
      descriptionEn:
        '14k white gold band with contemporary styling and high-polish finish. Modern elegance meets traditional craftsmanship.',
      descriptionHe:
        'טבעת זהב לבן 14 קראט עם עיצוב עכשווי וגימור מלוטש גבוה. אלגנטיות מודרנית פוגשת אומנות מסורתית.',
      price: 1699,
      image: '/images/product-5.jpg',
      images: [
        '/images/product-5.jpg',
        '/images/rings.jpg',
        '/images/wedding-rinfs.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: true,
      inventory: 14,
      categoryId: categories[1].id,
      sku: 'WGH-009',
      lowStockThreshold: 4,
      reorderPoint: 10,
      reorderQuantity: 18,
    },
    {
      name: 'Vintage Gold Band',
      nameEn: 'Vintage Gold Band',
      nameHe: "טבעת זהב וינטאג'",
      slug: 'vintage-gold-band',
      description: 'Vintage-inspired gold band with milgrain detailing.',
      descriptionEn:
        'Vintage-inspired gold band with intricate milgrain detailing and antique finish. Timeless design with old-world charm.',
      descriptionHe:
        "טבעת זהב בהשראת וינטאג' עם פירוט מילגריין מורכב וגימור עתיק. עיצוב נצחי עם קסם של עולם ישן.",
      price: 2199,
      comparePrice: 2599,
      image: '/images/ring-4.jpg',
      images: [
        '/images/ring-4.jpg',
        '/images/wedding-rinfs.jpg',
        '/images/product-1.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 8,
      categoryId: categories[1].id,
      sku: 'VGB-010',
      lowStockThreshold: 3,
      reorderPoint: 6,
      reorderQuantity: 12,
    },

    // Custom Pieces (Category 2)
    {
      name: 'Meteorite Inlay Ring',
      nameEn: 'Meteorite Inlay Ring',
      nameHe: 'טבעת עם שיבוץ מטאוריט',
      slug: 'meteorite-inlay-ring',
      description:
        'Unique titanium ring with authentic Gibeon meteorite inlay.',
      descriptionEn:
        'Extraordinary titanium ring featuring authentic Gibeon meteorite inlay with stunning Widmanstätten patterns formed over 4 billion years ago.',
      descriptionHe:
        'טבעת טיטניום יוצאת דופן עם שיבוץ מטאוריט גיבאון אותנטי עם דוגמאות וידמנשטטן מהממות שנוצרו לפני 4 מיליארד שנה.',
      price: 1599,
      image: '/images/ring-4.jpg',
      images: [
        '/images/ring-4.jpg',
        '/images/product-5.jpg',
        '/images/rings.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 5,
      categoryId: categories[2].id,
      sku: 'MIR-011',
      lowStockThreshold: 2,
      reorderPoint: 4,
      reorderQuantity: 8,
    },
    {
      name: 'Dragon Scale Custom',
      nameEn: 'Dragon Scale Custom',
      nameHe: 'קשקשי דרקון מותאם',
      slug: 'dragon-scale-custom',
      description: 'Hand-engraved dragon scale pattern ring.',
      descriptionEn:
        'Masterfully hand-engraved dragon scale pattern ring crafted in premium steel. Each scale individually detailed by master artisans.',
      descriptionHe:
        'טבעת בדוגמת קשקשי דרקון חרוטה ביד באופן מופתי, עשויה מפלדה איכותית. כל קשקש מפורט בנפרד על ידי אומנים מאסטרים.',
      price: 2299,
      image: '/images/product-1.jpg',
      images: [
        '/images/product-1.jpg',
        '/images/ring-black-bg.png',
        '/images/product-3.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 3,
      categoryId: categories[2].id,
      sku: 'DSC-012',
      lowStockThreshold: 1,
      reorderPoint: 2,
      reorderQuantity: 5,
    },
    {
      name: 'Celtic Knot Heritage',
      nameEn: 'Celtic Knot Heritage',
      nameHe: 'מורשת קשר קלטי',
      slug: 'celtic-knot-heritage',
      description: 'Traditional Celtic knot pattern in silver.',
      descriptionEn:
        'Traditional Celtic knot pattern meticulously carved in sterling silver. Represents eternal love and unity with ancient symbolism.',
      descriptionHe:
        'דוגמת קשר קלטי מסורתי חרוטה בקפידה בכסף סטרלינג. מייצגת אהבה נצחית ואחדות עם סמליות עתיקה.',
      price: 899,
      comparePrice: 1199,
      image: '/images/product-2.jpg',
      images: [
        '/images/product-2.jpg',
        '/images/rings.jpg',
        '/images/product-4.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: true,
      inventory: 7,
      categoryId: categories[2].id,
      sku: 'CKH-013',
      lowStockThreshold: 2,
      reorderPoint: 5,
      reorderQuantity: 10,
    },
    {
      name: 'Samurai Steel',
      nameEn: 'Samurai Steel',
      nameHe: 'פלדת סמוראי',
      slug: 'samurai-steel',
      description: 'Japanese-inspired steel ring with katana finish.',
      descriptionEn:
        'Japanese-inspired steel ring with authentic katana blade finish. Honored traditions meet modern craftsmanship.',
      descriptionHe:
        'טבעת פלדה בהשראה יפנית עם גימור להב קטאנה אותנטי. מסורות מכובדות פוגשות אומנות מודרנית.',
      price: 1299,
      image: '/images/ring-black-bg.png',
      images: [
        '/images/ring-black-bg.png',
        '/images/product-3.jpg',
        '/images/product-1.jpg',
      ],
      inStock: false,
      featured: false,
      freeShipping: true,
      inventory: 0,
      categoryId: categories[2].id,
      sku: 'SS-014',
      lowStockThreshold: 2,
      reorderPoint: 4,
      reorderQuantity: 8,
    },
    {
      name: 'Mystic Opal Inlay',
      nameEn: 'Mystic Opal Inlay',
      nameHe: 'שיבוץ אופל מיסטי',
      slug: 'mystic-opal-inlay',
      description: 'Titanium ring with genuine Australian opal inlay.',
      descriptionEn:
        'Titanium ring featuring genuine Australian opal inlay with mesmerizing color play. Each stone displays unique fire patterns.',
      descriptionHe:
        'טבעת טיטניום עם שיבוץ אופל אוסטרלי אמיתי עם משחק צבעים מהפנט. כל אבן מציגה דפוסי אש ייחודיים.',
      price: 1799,
      comparePrice: 2199,
      image: '/images/product-4.jpg',
      images: [
        '/images/product-4.jpg',
        '/images/ring-4.jpg',
        '/images/product-5.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 4,
      categoryId: categories[2].id,
      sku: 'MOI-015',
      lowStockThreshold: 1,
      reorderPoint: 3,
      reorderQuantity: 6,
    },

    // Necklaces (Category 3)
    {
      name: 'Steel Chain Classic',
      nameEn: 'Steel Chain Classic',
      nameHe: 'שרשרת פלדה קלאסית',
      slug: 'steel-chain-classic',
      description: 'Premium stainless steel chain necklace.',
      descriptionEn:
        'Premium stainless steel chain necklace with polished finish. Durable and sophisticated for everyday wear.',
      descriptionHe:
        'שרשרת פלדת אל-חלד איכותית עם גימור מלוטש. עמידה ומתוחכמת ללבישה יומיומית.',
      price: 399,
      image: '/images/necklace.jpg',
      images: [
        '/images/necklace.jpg',
        '/images/product-1.jpg',
        '/images/product-2.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: false,
      inventory: 30,
      categoryId: categories[3].id,
      sku: 'SCC-016',
      lowStockThreshold: 10,
      reorderPoint: 20,
      reorderQuantity: 40,
    },
    {
      name: 'Gold Link Chain',
      nameEn: 'Gold Link Chain',
      nameHe: 'שרשרת זהב מקושרת',
      slug: 'gold-link-chain',
      description: '14k gold plated link chain necklace.',
      descriptionEn:
        '14k gold plated link chain necklace with secure clasp. Elegant and versatile for any occasion.',
      descriptionHe:
        'שרשרת מקושרת מצופה זהב 14 קראט עם סגר בטוח. אלגנטית ורב-תכליתית לכל אירוע.',
      price: 599,
      comparePrice: 799,
      image: '/images/product-3.jpg',
      images: [
        '/images/product-3.jpg',
        '/images/necklace.jpg',
        '/images/product-4.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: true,
      inventory: 22,
      categoryId: categories[3].id,
      sku: 'GLC-017',
      lowStockThreshold: 8,
      reorderPoint: 15,
      reorderQuantity: 25,
    },
    {
      name: 'Silver Pendant Chain',
      nameEn: 'Silver Pendant Chain',
      nameHe: 'שרשרת תליון כסף',
      slug: 'silver-pendant-chain',
      description: 'Sterling silver chain with custom pendant.',
      descriptionEn:
        'Sterling silver chain with customizable pendant option. Premium quality with lifetime polish guarantee.',
      descriptionHe:
        'שרשרת כסף סטרלינג עם אפשרות תליון הניתן להתאמה אישית. איכות פרמיום עם ערבות ליטוש לכל החיים.',
      price: 699,
      image: '/images/product-5.jpg',
      images: [
        '/images/product-5.jpg',
        '/images/necklace.jpg',
        '/images/product-1.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 18,
      categoryId: categories[3].id,
      sku: 'SPC-018',
      lowStockThreshold: 6,
      reorderPoint: 12,
      reorderQuantity: 20,
    },
    {
      name: 'Leather Cord Chain',
      nameEn: 'Leather Cord Chain',
      nameHe: 'שרשרת חוט עור',
      slug: 'leather-cord-chain',
      description: 'Premium leather cord with steel accents.',
      descriptionEn:
        'Premium leather cord necklace with stainless steel accents and magnetic clasp. Modern casual elegance.',
      descriptionHe:
        "שרשרת חוט עור איכותית עם מבטאי פלדת אל-חלד וסגר מגנטי. אלגנטיות קז'ואל מודרנית.",
      price: 299,
      image: '/images/product-2.jpg',
      images: [
        '/images/product-2.jpg',
        '/images/necklace.jpg',
        '/images/product-3.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: false,
      inventory: 35,
      categoryId: categories[3].id,
      sku: 'LCC-019',
      lowStockThreshold: 12,
      reorderPoint: 25,
      reorderQuantity: 50,
    },
    {
      name: 'Byzantine Gold Chain',
      nameEn: 'Byzantine Gold Chain',
      nameHe: 'שרשרת זהב ביזנטית',
      slug: 'byzantine-gold-chain',
      description: 'Intricate Byzantine pattern gold chain.',
      descriptionEn:
        'Intricate Byzantine pattern gold chain with traditional weave design. Sophisticated luxury piece.',
      descriptionHe:
        'שרשרת זהב בדוגמה ביזנטית מורכבת עם עיצוב אריגה מסורתי. יצירת יוקרה מתוחכמת.',
      price: 1299,
      comparePrice: 1599,
      image: '/images/necklace.jpg',
      images: [
        '/images/necklace.jpg',
        '/images/product-4.jpg',
        '/images/product-5.jpg',
      ],
      inStock: false,
      featured: true,
      freeShipping: true,
      inventory: 0,
      categoryId: categories[3].id,
      sku: 'BGC-020',
      lowStockThreshold: 3,
      reorderPoint: 6,
      reorderQuantity: 10,
    },

    // Bracelets (Category 4)
    {
      name: 'Steel Link Bracelet',
      nameEn: 'Steel Link Bracelet',
      nameHe: 'צמיד פלדה מקושר',
      slug: 'steel-link-bracelet',
      description: 'Heavy-duty steel link bracelet with secure clasp.',
      descriptionEn:
        'Heavy-duty steel link bracelet with secure clasp and polished finish. Built for strength and style.',
      descriptionHe:
        'צמיד פלדה מקושר כבד עם סגר בטוח וגימור מלוטש. בנוי לחוזק וסטייל.',
      price: 499,
      image: '/images/product-1.jpg',
      images: [
        '/images/product-1.jpg',
        '/images/product-2.jpg',
        '/images/product-3.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 25,
      categoryId: categories[4].id,
      sku: 'SLB-021',
      lowStockThreshold: 8,
      reorderPoint: 15,
      reorderQuantity: 30,
    },
    {
      name: 'Leather Wrap Bracelet',
      nameEn: 'Leather Wrap Bracelet',
      nameHe: 'צמיד עור כרוך',
      slug: 'leather-wrap-bracelet',
      description: 'Premium leather wrap bracelet with steel accents.',
      descriptionEn:
        'Premium leather wrap bracelet with stainless steel accents and adjustable closure. Casual sophistication.',
      descriptionHe:
        "צמיד עור כרוך איכותי עם מבטאי פלדת אל-חלד וסגירה מתכווננת. תחכום קז'ואל.",
      price: 349,
      comparePrice: 449,
      image: '/images/product-4.jpg',
      images: [
        '/images/product-4.jpg',
        '/images/product-5.jpg',
        '/images/product-1.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: false,
      inventory: 40,
      categoryId: categories[4].id,
      sku: 'LWB-022',
      lowStockThreshold: 15,
      reorderPoint: 30,
      reorderQuantity: 60,
    },
    {
      name: 'Gold Cuff Bracelet',
      nameEn: 'Gold Cuff Bracelet',
      nameHe: 'צמיד זהב עמיד',
      slug: 'gold-cuff-bracelet',
      description: '14k gold plated cuff bracelet with engraved design.',
      descriptionEn:
        '14k gold plated cuff bracelet with intricate engraved design. Statement piece for special occasions.',
      descriptionHe:
        'צמיד זהב מצופה 14 קראט עם עיצוב חרוט מורכב. יצירת הצהרה לאירועים מיוחדים.',
      price: 799,
      image: '/images/product-2.jpg',
      images: [
        '/images/product-2.jpg',
        '/images/product-3.jpg',
        '/images/product-4.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 12,
      categoryId: categories[4].id,
      sku: 'GCB-023',
      lowStockThreshold: 4,
      reorderPoint: 8,
      reorderQuantity: 15,
    },
    {
      name: 'Titanium Sports Band',
      nameEn: 'Titanium Sports Band',
      nameHe: 'רצועת ספורט טיטניום',
      slug: 'titanium-sports-band',
      description: 'Lightweight titanium sports bracelet.',
      descriptionEn:
        'Lightweight titanium sports bracelet with water-resistant design. Perfect for active lifestyle.',
      descriptionHe:
        'צמיד ספורט טיטניום קל במשקל עם עיצוב עמיד למים. מושלם לאורח חיים פעיל.',
      price: 599,
      comparePrice: 749,
      image: '/images/product-5.jpg',
      images: [
        '/images/product-5.jpg',
        '/images/product-1.jpg',
        '/images/product-2.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: true,
      inventory: 20,
      categoryId: categories[4].id,
      sku: 'TSB-024',
      lowStockThreshold: 7,
      reorderPoint: 15,
      reorderQuantity: 25,
    },
    {
      name: 'Rope Chain Bracelet',
      nameEn: 'Rope Chain Bracelet',
      nameHe: 'צמיד שרשרת חבל',
      slug: 'rope-chain-bracelet',
      description: 'Twisted rope pattern steel bracelet.',
      descriptionEn:
        'Twisted rope pattern steel bracelet with diamond-cut finish. Classic design with modern durability.',
      descriptionHe:
        'צמיד פלדה בדוגמת חבל מעוותת עם גימור חיתוך יהלום. עיצוב קלאסי עם עמידות מודרנית.',
      price: 449,
      image: '/images/product-3.jpg',
      images: [
        '/images/product-3.jpg',
        '/images/product-4.jpg',
        '/images/product-5.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: false,
      inventory: 28,
      categoryId: categories[4].id,
      sku: 'RCB-025',
      lowStockThreshold: 10,
      reorderPoint: 20,
      reorderQuantity: 35,
    },

    // Additional Premium Pieces
    {
      name: 'Obsidian Black Elite',
      nameEn: 'Obsidian Black Elite',
      nameHe: 'אלית שחור אובסידיאן',
      slug: 'obsidian-black-elite',
      description: 'Premium black ceramic ring with tungsten core.',
      descriptionEn:
        'Premium black ceramic ring with tungsten carbide core. Exceptional durability meets sophisticated aesthetics.',
      descriptionHe:
        'טבעת קרמיקה שחורה איכותית עם ליבת קרביד טונגסטן. עמידות יוצאת דופן פוגשת אסתטיקה מתוחכמת.',
      price: 999,
      comparePrice: 1299,
      image: '/images/ring-black-bg.png',
      images: [
        '/images/ring-black-bg.png',
        '/images/product-1.jpg',
        '/images/product-2.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 11,
      categoryId: categories[0].id,
      sku: 'OBE-026',
      lowStockThreshold: 3,
      reorderPoint: 8,
      reorderQuantity: 15,
    },
    {
      name: 'Royal Gold Wedding',
      nameEn: 'Royal Gold Wedding',
      nameHe: 'חתונת זהב מלכותית',
      slug: 'royal-gold-wedding',
      description: 'Luxury 18k gold wedding band with diamond accents.',
      descriptionEn:
        'Luxury 18k gold wedding band with subtle diamond accents. Royal elegance for your special day.',
      descriptionHe:
        'טבעת נישואין יוקרתית מזהב 18 קראט עם מבטאי יהלום עדינים. אלגנטיות מלכותית ליום המיוחד שלכם.',
      price: 3999,
      comparePrice: 4599,
      image: '/images/wedding-rinfs.jpg',
      images: [
        '/images/wedding-rinfs.jpg',
        '/images/rings.jpg',
        '/images/product-3.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 4,
      categoryId: categories[1].id,
      sku: 'RGW-027',
      lowStockThreshold: 1,
      reorderPoint: 3,
      reorderQuantity: 6,
    },
    {
      name: 'Ancient Rune Custom',
      nameEn: 'Ancient Rune Custom',
      nameHe: 'רונה עתיקה מותאמת',
      slug: 'ancient-rune-custom',
      description: 'Custom engraved ancient rune pattern ring.',
      descriptionEn:
        'Custom engraved ancient rune pattern ring with personalized inscription. Connect with ancient wisdom.',
      descriptionHe:
        'טבעת בדוגמת רונה עתיקה חרוטה בהתאמה אישית עם כתובת אישית. התחברות לחוכמה עתיקה.',
      price: 1899,
      image: '/images/product-4.jpg',
      images: [
        '/images/product-4.jpg',
        '/images/ring-4.jpg',
        '/images/product-5.jpg',
      ],
      inStock: false,
      featured: true,
      freeShipping: true,
      inventory: 0,
      categoryId: categories[2].id,
      sku: 'ARC-028',
      lowStockThreshold: 1,
      reorderPoint: 2,
      reorderQuantity: 4,
    },
    {
      name: 'Platinum Statement Chain',
      nameEn: 'Platinum Statement Chain',
      nameHe: 'שרשרת הצהרה פלטינה',
      slug: 'platinum-statement-chain',
      description: 'Heavy platinum chain for ultimate luxury.',
      descriptionEn:
        'Heavy platinum chain necklace for ultimate luxury statement. Unmatched prestige and durability.',
      descriptionHe:
        'שרשרת פלטינה כבדה להצהרת יוקרה אולטימטיבית. יוקרה ועמידות ללא תחרות.',
      price: 4999,
      image: '/images/necklace.jpg',
      images: [
        '/images/necklace.jpg',
        '/images/product-5.jpg',
        '/images/product-1.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 2,
      categoryId: categories[3].id,
      sku: 'PSC-029',
      lowStockThreshold: 1,
      reorderPoint: 2,
      reorderQuantity: 3,
    },
    {
      name: 'Diamond Steel Cuff',
      nameEn: 'Diamond Steel Cuff',
      nameHe: 'אזיקי פלדה יהלום',
      slug: 'diamond-steel-cuff',
      description: 'Steel cuff bracelet with genuine diamond inlay.',
      descriptionEn:
        'Steel cuff bracelet with genuine diamond inlay and precision engineering. Where strength meets brilliance.',
      descriptionHe:
        'צמיד פלדה עם שיבוץ יהלום אמיתי והנדסה מדויקת. היכן שחוזק פוגש ברק.',
      price: 2799,
      comparePrice: 3299,
      image: '/images/product-2.jpg',
      images: [
        '/images/product-2.jpg',
        '/images/product-3.jpg',
        '/images/product-4.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 3,
      categoryId: categories[4].id,
      sku: 'DSC-030',
      lowStockThreshold: 1,
      reorderPoint: 2,
      reorderQuantity: 4,
    },

    {
      name: 'Obsidian Steel Ring',
      nameEn: 'Obsidian Steel Ring',
      nameHe: 'טבעת פלדת אובסידיאן',
      slug: 'obsidian-steel-ring',
      description:
        'A bold statement piece crafted from premium tungsten carbide with a brushed matte finish. Perfect for the modern gentleman.',
      descriptionEn:
        'A bold statement piece crafted from premium tungsten carbide with a brushed matte finish. Perfect for the modern gentleman who values durability and style. This ring features exceptional scratch resistance and a contemporary design.',
      descriptionHe:
        "יצירת אמנות נועזת המיוצרת מקרביד טונגסטן פרימיום עם גימור מט מוברש. מושלם לג'נטלמן המודרני המעריך עמידות וסטייל. הטבעת מציגה עמידות יוצאת דופן בפני שריטות ועיצוב עכשווי.",
      price: 899,
      comparePrice: 1299,
      image: '/images/ring-4.jpg',
      images: [
        '/images/ring-4.jpg',
        '/images/ring-black-bg.png',
        '/images/rings.jpg',
        '/images/product-1.jpg',
        '/images/ring-1-lifestyle.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 15,
      categoryId: categories[0].id,
    },
    {
      name: 'Damascus Steel Band',
      nameEn: 'Damascus Steel Band',
      nameHe: 'טבעת פלדת דמשק',
      slug: 'damascus-steel-band',
      description:
        'Hand-forged Damascus steel ring with unique pattern. Each piece is one-of-a-kind.',
      descriptionEn:
        'Hand-forged Damascus steel ring featuring a mesmerizing wave pattern created through ancient metalworking techniques. Each piece is truly one-of-a-kind with its own unique pattern. The ring combines traditional craftsmanship with modern comfort.',
      descriptionHe:
        'טבעת פלדת דמשק מחושלת ידנית עם דוגמת גלים מהפנטת שנוצרה באמצעות טכניקות עתיקות של עיבוד מתכת. כל יצירה היא באמת ייחודית עם דוגמה משלה. הטבעת משלבת אומנות מסורתית עם נוחות מודרנית.',
      price: 1299,
      comparePrice: 1799,
      image: '/images/ring-2.jpg',
      images: [
        '/images/ring-2.jpg',
        '/images/ring-2-pattern.jpg',
        '/images/ring-2-side.jpg',
        '/images/ring-2-detail.jpg',
        '/images/ring-2-hand.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 8,
      categoryId: categories[0].id,
    },
    {
      name: 'Eternal Gold Band',
      nameEn: 'Eternal Gold Band',
      nameHe: 'טבעת זהב נצחית',
      slug: 'eternal-gold-band',
      description:
        'Classic 18k gold wedding band with polished finish. Timeless elegance.',
      descriptionEn:
        'Classic 18k gold wedding band with mirror polished finish. A symbol of timeless elegance and eternal commitment. Crafted from solid gold with comfort-fit interior for all-day wear. Perfect for those who appreciate traditional luxury.',
      descriptionHe:
        'טבעת נישואין קלאסית מזהב 18 קראט עם גימור מלוטש למראה מראה. סמל של אלגנטיות נצחית ומחויבות נצחית. מעוצבת מזהב מלא עם פנים מתאים לנוחות למשך כל היום. מושלמת למי שמעריך יוקרה מסורתית.',
      price: 2499,
      comparePrice: 2999,
      image: '/images/ring-3.jpg',
      images: [
        '/images/ring-3.jpg',
        '/images/ring-3-shine.jpg',
        '/images/ring-3-angle.jpg',
        '/images/ring-3-pair.jpg',
        '/images/ring-3-box.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 12,
      categoryId: categories[1].id,
    },
    {
      name: 'Carbon Fiber Ring',
      nameEn: 'Carbon Fiber Ring',
      nameHe: 'טבעת סיבי פחמן',
      slug: 'carbon-fiber-ring',
      description:
        'Modern design combining aerospace-grade carbon fiber with titanium.',
      descriptionEn:
        'Ultra-modern design combining aerospace-grade carbon fiber with surgical titanium. Incredibly lightweight yet extremely durable. The unique weave pattern creates a sophisticated tech-inspired aesthetic. Perfect for those who live on the cutting edge.',
      descriptionHe:
        'עיצוב אולטרה-מודרני המשלב סיבי פחמן בדרגה אווירית עם טיטניום כירורגי. קל במשקל להפליא אך עמיד במיוחד. דוגמת האריגה הייחודית יוצרת אסתטיקה מתוחכמת בהשראת טכנולוגיה. מושלם למי שחי בקצה החדשני.',
      price: 699,
      image: '/images/ring-black-bg.png',
      images: [
        '/images/ring-black-bg.png',
        '/images/ring-4.jpg',
        '/images/rings.jpg',
        '/images/product-2.jpg',
        '/images/ring-1-modern.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: true,
      inventory: 20,
      categoryId: categories[0].id,
    },
    {
      name: 'Platinum Classic',
      nameEn: 'Platinum Classic',
      nameHe: 'פלטינה קלאסית',
      slug: 'platinum-classic',
      description: 'Sophisticated platinum band with comfort fit interior.',
      descriptionEn:
        "Sophisticated platinum band with comfort fit interior and refined brushed finish. Platinum's natural white luster and exceptional durability make it the ultimate choice for wedding bands. Hypoallergenic and tarnish-resistant for lifetime wear.",
      descriptionHe:
        'טבעת פלטינה מתוחכמת עם פנים נוחים וגימור מוברש מעודן. הברק הלבן הטבעי והעמידות היוצאת מן הכלל של הפלטינה הופכים אותה לבחירה האולטימטיבית לטבעות נישואין. היפואלרגנית ועמידה בפני השחתה ללבישה כל החיים.',
      price: 3299,
      comparePrice: 3799,
      image: '/images/ring-2.jpg',
      images: [
        '/images/ring-2.jpg',
        '/images/ring-2-platinum.jpg',
        '/images/ring-2-white.jpg',
        '/images/ring-2-elegant.jpg',
        '/images/ring-2-luxury.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: true,
      inventory: 6,
      categoryId: categories[1].id,
    },
    {
      name: 'Meteorite Inlay Ring',
      nameEn: 'Meteorite Inlay Ring',
      nameHe: 'טבעת עם שיבוץ מטאוריט',
      slug: 'meteorite-inlay-ring',
      description:
        'Unique titanium ring with authentic Gibeon meteorite inlay.',
      descriptionEn:
        'Extraordinary titanium ring featuring authentic Gibeon meteorite inlay with stunning Widmanstätten patterns. This meteorite formed over 4 billion years ago and traveled through space before landing in Namibia. Each ring contains a genuine piece of space history with its own unique crystalline structure.',
      descriptionHe:
        'טבעת טיטניום יוצאת דופן עם שיבוץ מטאוריט גיבאון אותנטי עם דוגמאות וידמנשטטן מהממות. מטאוריט זה נוצר לפני למעלה מ-4 מיליארד שנה ועבר במרחבי החלל לפני שנחת בנמיביה. כל טבעת מכילה חתיכה אמיתית של היסטוריה חללית עם מבנה גבישי ייחודי משלה.',
      price: 1599,
      image: '/images/ring-3.jpg',
      images: [
        '/images/ring-3.jpg',
        '/images/ring-3-space.jpg',
        '/images/ring-3-pattern-detail.jpg',
        '/images/ring-3-meteorite.jpg',
        '/images/ring-3-cosmic.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 5,
      categoryId: categories[2].id,
    },
    {
      name: 'Black Zirconium Band',
      nameEn: 'Black Zirconium Band',
      nameHe: 'טבעת זירקוניום שחור',
      slug: 'black-zirconium-band',
      description:
        'Sleek black zirconium ring with natural ceramic oxide finish.',
      descriptionEn:
        "Sleek black zirconium band with permanent black ceramic oxide finish. Created through a specialized heating process that transforms the metal's surface into ultra-hard black ceramic. Scratch-resistant, hypoallergenic, and maintains its deep black color for life. Modern sophistication meets durability.",
      descriptionHe:
        'טבעת זירקוניום שחורה מלוטשה עם גימור תחמוצת קרמית שחורה קבועה. נוצרת באמצעות תהליך חימום מיוחד שהופך את פני השטח של המתכת לקרמיקה שחורה קשה במיוחד. עמידה בפני שריטות, היפואלרגנית ושומרת על הצבע השחור העמוק שלה לכל החיים. תחכום מודרני פוגש עמידות.',
      price: 799,
      comparePrice: 999,
      image: '/images/ring-black-bg.png',
      images: [
        '/images/ring-black-bg.png',
        '/images/ring-4.jpg',
        '/images/rings.jpg',
        '/images/product-3.jpg',
        '/images/product-4.jpg',
      ],
      inStock: true,
      featured: true,
      freeShipping: true,
      inventory: 18,
      categoryId: categories[0].id,
    },
    {
      name: 'Rose Gold Elegance',
      nameEn: 'Rose Gold Elegance',
      nameHe: 'אלגנטיות זהב ורוד',
      slug: 'rose-gold-elegance',
      description: 'Romantic 14k rose gold band with brushed finish.',
      descriptionEn:
        'Romantic 14k rose gold band with brushed finish and beveled edges. The warm pink hue of rose gold creates a unique and contemporary look. The copper alloy gives it exceptional durability while maintaining its distinctive color. A perfect blend of modern style and classic romance.',
      descriptionHe:
        'טבעת זהב ורוד רומנטית 14 קראט עם גימור מוברש וקצוות משופעים. הגוון הוורוד החם של זהב ורוד יוצר מראה ייחודי ועכשווי. סגסוגת הנחושת מעניקה לה עמידות יוצאת מן הכלל תוך שמירה על הצבע הייחודי שלה. שילוב מושלם של סטייל מודרני ורומנטיקה קלאסית.',
      price: 1899,
      comparePrice: 2299,
      image: '/images/ring-2.jpg',
      images: [
        '/images/ring-2.jpg',
        '/images/ring-2-rose.jpg',
        '/images/ring-2-pink.jpg',
        '/images/ring-2-warm.jpg',
        '/images/ring-2-romantic.jpg',
      ],
      inStock: true,
      featured: false,
      freeShipping: true,
      inventory: 10,
      categoryId: categories[1].id,
    },
  ];

  // Create all products
  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: {},
      create: product,
    });
  }

  console.log('Products created:', products.length);
  console.log('Seeding finished.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
